// Generated by CoffeeScript 1.4.0
(function() {
  var app, context, mainctrl;

  app = angular.module('msprop', []);

  app.config(function($routeProvider) {
    return $routeProvider.when('/home', {
      templateUrl: "/partials/home.html"
    }).when('/about', {
      templateUrl: "/partials/about.html"
    }).when('/contact', {
      templateUrl: "/partials/contact.html"
    }).when('/testimonials', {
      templateUrl: "/partials/testimonials.html"
    }).when('/services', {
      templateUrl: "/partials/services.html"
    }).otherwise('/', {
      redirectTo: "/home"
    });
  });

  mainctrl = function($scope, $location) {
    $scope.init = function() {
      return $location.path("/home");
    };
    return $scope.navigate = function(page) {
      return $location.path("/" + page);
    };
  };

  context = typeof exports !== "undefined" && exports !== null ? exports : this;

  context.app = app;

  context.mainctrl = mainctrl;

}).call(this);
