// Generated by CoffeeScript 1.4.0
(function() {
  var app, context, mainctrl;

  app = angular.module('msprop', []);

  app.config(function($routeProvider) {
    return $routeProvider.when('/home', {
      templateUrl: "/partials/home.html"
    }).when('/about', {
      templateUrl: "/partials/about.html"
    }).when('/contact', {
      templateUrl: "/partials/contact.html"
    }).when('/testimonials', {
      templateUrl: "/partials/testimonials.html"
    }).when('/services', {
      templateUrl: "/partials/services.html"
    }).otherwise('/', {
      redirectTo: "/home"
    });
  });

  app.directive('navpill', function($location) {
    return {
      restrict: 'E',
      template: "<li class=\"{{active}}\"><a ng-click=\"navigate('{{page}}')\">{{label}}</a></li>",
      replace: true,
      scope: {
        page: '@',
        label: '@'
      },
      controller: function($scope, $element, $attrs) {
        return $scope.active = $location.path().search($attrs.page) !== -1 ? 'active' : '';
      }
    };
  });

  mainctrl = function($scope, $location) {
    $scope.init = function() {
      return $location.path($location.path());
    };
    return $scope.navigate = function(page) {
      return $location.path("/" + page);
    };
  };

  context = typeof exports !== "undefined" && exports !== null ? exports : this;

  context.app = app;

  context.mainctrl = mainctrl;

}).call(this);
